import { Transition } from '@headlessui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Header';
import Homepg from '../components/homepage';
import Services from '../components/services';
import Gallery from '../components/gallery'
import Review from '../components/review'
import Footer from '../components/footer'

const Home: NextPage = () => {
  return (
   <div>
      <Head>
        <title>Travel Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/**Header Section */}
        <Navbar/>
        {/**Home page section */}
        <Homepg/>
        {/**Services section */}
        <Services/>
        {/**Gallery section */}
        <Gallery/>
        {/**Review section */}
        <Review/>  
        {/**Footer section */}
        <Footer/>
     
     </div>
    </div>
  )
}

export default Home
